"""cards: external ids + json attributes for CardLists

Revision ID: aa13de0b4e65
Revises: 1b493e9363ca
Create Date: 2025-08-22 21:24:36.623220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa13de0b4e65'
down_revision: Union[str, Sequence[str], None] = '1b493e9363ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('external_source', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('attributes_json', sa.Text(), nullable=True))
    op.add_column('cards', sa.Column('variations_json', sa.Text(), nullable=True))
    op.add_column('cards', sa.Column('parallels_json', sa.Text(), nullable=True))
    op.add_column('cards', sa.Column('is_rc', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'is_rc')
    op.drop_column('cards', 'parallels_json')
    op.drop_column('cards', 'variations_json')
    op.drop_column('cards', 'attributes_json')
    op.drop_column('cards', 'external_id')
    op.drop_column('cards', 'external_source')
    # ### end Alembic commands ###
