"""init schema v1

Revision ID: eed5c7b2854b
Revises: 
Create Date: 2025-08-22 15:42:05.350628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed5c7b2854b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('card_uuid', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('set_name', sa.String(), nullable=True),
    sa.Column('subset', sa.String(), nullable=True),
    sa.Column('card_no', sa.String(), nullable=True),
    sa.Column('player', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('parallel', sa.String(), nullable=True),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('print_run', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('canonical_key', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('updated_by_user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('card_uuid'),
    sa.UniqueConstraint('tenant_id', 'canonical_key', name='ux_cards_tenant_canonical')
    )
    op.create_index(op.f('ix_cards_canonical_key'), 'cards', ['canonical_key'], unique=False)
    op.create_index(op.f('ix_cards_player'), 'cards', ['player'], unique=False)
    op.create_index(op.f('ix_cards_tenant_id'), 'cards', ['tenant_id'], unique=False)
    op.create_table('ownership',
    sa.Column('ownership_uuid', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('card_uuid', sa.String(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=True),
    sa.Column('grade_scale', sa.String(), nullable=True),
    sa.Column('grade_value', sa.String(), nullable=True),
    sa.Column('cert_no', sa.String(), nullable=True),
    sa.Column('acquired_date', sa.String(), nullable=True),
    sa.Column('price_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_uuid'], ['cards.card_uuid'], ),
    sa.PrimaryKeyConstraint('ownership_uuid')
    )
    op.create_index(op.f('ix_ownership_tenant_id'), 'ownership', ['tenant_id'], unique=False)
    op.create_table('prices',
    sa.Column('price_uuid', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('card_uuid', sa.String(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=True),
    sa.Column('grade_scale', sa.String(), nullable=True),
    sa.Column('grade_value', sa.String(), nullable=True),
    sa.Column('sale_date', sa.String(), nullable=True),
    sa.Column('source_market', sa.String(), nullable=True),
    sa.Column('source_lot_url', sa.Text(), nullable=True),
    sa.Column('amount_all_in', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('fees_included', sa.String(), nullable=True),
    sa.Column('buyer_premium_pct', sa.String(), nullable=True),
    sa.Column('is_ask_or_bid', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_uuid'], ['cards.card_uuid'], ),
    sa.PrimaryKeyConstraint('price_uuid')
    )
    op.create_index(op.f('ix_prices_tenant_id'), 'prices', ['tenant_id'], unique=False)
    op.create_table('media',
    sa.Column('media_uuid', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('ownership_uuid', sa.String(), nullable=True),
    sa.Column('card_uuid', sa.String(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('phash', sa.String(), nullable=True),
    sa.Column('width', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('filesize_bytes', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_uuid'], ['cards.card_uuid'], ),
    sa.ForeignKeyConstraint(['ownership_uuid'], ['ownership.ownership_uuid'], ),
    sa.PrimaryKeyConstraint('media_uuid')
    )
    op.create_index(op.f('ix_media_tenant_id'), 'media', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_tenant_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_prices_tenant_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_ownership_tenant_id'), table_name='ownership')
    op.drop_table('ownership')
    op.drop_index(op.f('ix_cards_tenant_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_player'), table_name='cards')
    op.drop_index(op.f('ix_cards_canonical_key'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
